{"errorMessage": "The official Pinecone python package has been renamed from `pinecone-client` to `pinecone`. Please remove `pinecone-client` from your project dependencies and add `pinecone` instead. See the README at https://github.com/pinecone-io/pinecone-python-client for more information on using the python SDK.", "errorType": "Exception", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1204, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n", "  File \"/var/task/chat_handler.py\", line 23, in <module>\n    from file_processing.vector_storage import vector_storage, format_rag_context\n", "  File \"/var/task/file_processing/vector_storage.py\", line 15, in <module>\n    from pinecone import Pinecone\n", "  File \"/var/task/pinecone/__init__.py\", line 5, in <module>\n    raise Exception(\n"]}